"""
claude_inline_samples.py
========================

52 hand-crafted SPICE netlists for SFT training, one batch per constraint
in pipeline/data/datasets/constraints.json.  Generated by Claude (in
conversation, not via API) with explicit physics calculations:

    Buck:        D = Vout / Vin              ;  t_on = D * period
    Boost:       D = 1 - Vin / Vout          ;  t_on = D * period
    SEPIC (BB):  D = Vout / (Vin + Vout)     ;  t_on = D * period
    Rload     = Vout^2 / Pin

Per constraint, 4 variants:
    - different Vin within the [vin_min, vin_max] range
    - different topology (async / sync / interleaved for buck-only,
      single-stage variants for boost, SEPIC for buck-boost)
    - different L, C, period values for SFT diversity

Run this script once and it writes:
    data/sft/sft_from_claude_inline.jsonl
    pipeline/data/batch_sft_claude_inline_idx<N>/   (canonical layout)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from pipeline.llm_topology_generation.prompt_input import (
    load_constraints, make_prompt,
)
from pipeline.llm_topology_generation.net_writer import write_netlists


# ────────────────────────────────────────────────────────────────────────
# 52 SAMPLES — one entry per netlist, grouped by constraint_idx
# ────────────────────────────────────────────────────────────────────────

SAMPLES: list[dict] = [

# ── IDX 0: Vin 12-100V → 5V, 100W (buck) ───────────────────────────────
{"idx": 0, "tag": "12V-async",
 "net": """\
* 12V to 5V async buck, 100W, 100kHz
* D=5/12=0.4167, Rload=V^2/P=25/100=0.25
Vin in 0 12
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 100u
C1 out 0 470u
Rload out 0 0.25
Vgate gate 0 PULSE(0 12 0 1n 1n 4.17u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 0, "tag": "12V-sync",
 "net": """\
* 12V to 5V synchronous buck, 100W
* M2 replaces freewheel diode; Rbleed needed because sw has no static path
Vin in 0 12
M1 in gate sw 0 NMOS W=1 L=1
M2 sw gate2 0 0 NMOS W=1 L=1
L1 sw out 100u
C1 out 0 470u
Rload out 0 0.25
Rbleed sw 0 1Meg
Vgate  gate  0 PULSE(0 12 0    1n 1n 4.17u 10u)
Vgate2 gate2 0 PULSE(0 12 5.0u 1n 1n 4.83u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.tran 1n 5m
.end"""},

{"idx": 0, "tag": "12V-interleaved",
 "net": """\
* 12V to 5V interleaved 2-phase buck, 100W, 100kHz, 180-deg phase shift
Vin in 0 12
M1 in gate1 sw1 0 NMOS W=1 L=1
M2 in gate2 sw2 0 NMOS W=1 L=1
D1 0 sw1 DIODE
D2 0 sw2 DIODE
L1 sw1 out 47u
L2 sw2 out 47u
C1 out 0 220u
Rload out 0 0.25
Vgate1 gate1 0 PULSE(0 12 0  1n 1n 4.17u 10u)
Vgate2 gate2 0 PULSE(0 12 5u 1n 1n 4.17u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 0, "tag": "50V-async",
 "net": """\
* 50V to 5V async buck, 100W, 50kHz
* D=5/50=0.1, t_on=2u for T=20u
Vin in 0 50
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 220u
C1 out 0 470u
Rload out 0 0.25
Vgate gate 0 PULSE(0 12 0 1n 1n 2u 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 1: Vin 208-400V → 24V, 500W (buck) ─────────────────────────────
{"idx": 1, "tag": "240V-async",
 "net": """\
* 240V to 24V async buck, 500W, 100kHz
* D=24/240=0.1, t_on=1u, Rload=576/500=1.152
Vin in 0 240
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 47u
C1 out 0 220u
Rload out 0 1.152
Vgate gate 0 PULSE(0 12 0 1n 1n 1u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 1, "tag": "400V-async",
 "net": """\
* 400V to 24V async buck, 500W, 50kHz
* D=24/400=0.06, t_on=1.2u for T=20u
Vin in 0 400
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 100u
C1 out 0 220u
Rload out 0 1.152
Vgate gate 0 PULSE(0 12 0 1n 1n 1.2u 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 1, "tag": "280V-sync",
 "net": """\
* 280V to 24V synchronous buck, 500W
* D=24/280=0.0857, t_on=857n for T=10u
Vin in 0 280
M1 in gate sw 0 NMOS W=1 L=1
M2 sw gate2 0 0 NMOS W=1 L=1
L1 sw out 68u
C1 out 0 220u
Rload out 0 1.152
Rbleed sw 0 1Meg
Vgate  gate  0 PULSE(0 12 0    1n 1n 857n  10u)
Vgate2 gate2 0 PULSE(0 12 1.5u 1n 1n 8.0u  10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.tran 1n 5m
.end"""},

{"idx": 1, "tag": "300V-interleaved",
 "net": """\
* 300V to 24V interleaved 2-phase buck, 500W
* D=24/300=0.08, t_on=800n for T=10u
Vin in 0 300
M1 in gate1 sw1 0 NMOS W=1 L=1
M2 in gate2 sw2 0 NMOS W=1 L=1
D1 0 sw1 DIODE
D2 0 sw2 DIODE
L1 sw1 out 47u
L2 sw2 out 47u
C1 out 0 220u
Rload out 0 1.152
Vgate1 gate1 0 PULSE(0 12 0  1n 1n 800n 10u)
Vgate2 gate2 0 PULSE(0 12 5u 1n 1n 800n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 2: Vin 220-380V → 12V, 300W (buck) ─────────────────────────────
{"idx": 2, "tag": "220V-async",
 "net": """\
* 220V to 12V async buck, 300W, 100kHz
* D=12/220=0.0545, t_on=545n, Rload=144/300=0.48
Vin in 0 220
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 47u
C1 out 0 470u
Rload out 0 0.48
Vgate gate 0 PULSE(0 12 0 1n 1n 545n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 2, "tag": "380V-async",
 "net": """\
* 380V to 12V async buck, 300W, 100kHz
* D=12/380=0.0316, t_on=316n
Vin in 0 380
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 68u
C1 out 0 220u
Rload out 0 0.48
Vgate gate 0 PULSE(0 12 0 1n 1n 316n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 2, "tag": "300V-async-50kHz",
 "net": """\
* 300V to 12V async buck, 300W, 50kHz
* D=12/300=0.04, t_on=800n for T=20u
Vin in 0 300
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 100u
C1 out 0 470u
Rload out 0 0.48
Vgate gate 0 PULSE(0 12 0 1n 1n 800n 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 2, "tag": "250V-interleaved",
 "net": """\
* 250V to 12V interleaved 2-phase buck, 300W
* D=12/250=0.048, t_on=480n
Vin in 0 250
M1 in gate1 sw1 0 NMOS W=1 L=1
M2 in gate2 sw2 0 NMOS W=1 L=1
D1 0 sw1 DIODE
D2 0 sw2 DIODE
L1 sw1 out 47u
L2 sw2 out 47u
C1 out 0 220u
Rload out 0 0.48
Vgate1 gate1 0 PULSE(0 12 0  1n 1n 480n 10u)
Vgate2 gate2 0 PULSE(0 12 5u 1n 1n 480n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 3: Vin 230-400V → 5V, 150W (buck) ──────────────────────────────
{"idx": 3, "tag": "230V-async",
 "net": """\
* 230V to 5V async buck, 150W
* D=5/230=0.0217, t_on=217n, Rload=25/150=0.167
Vin in 0 230
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 22u
C1 out 0 470u
Rload out 0 0.167
Vgate gate 0 PULSE(0 12 0 1n 1n 217n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 3, "tag": "400V-async",
 "net": """\
* 400V to 5V async buck, 150W
* D=5/400=0.0125, t_on=125n
Vin in 0 400
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 47u
C1 out 0 470u
Rload out 0 0.167
Vgate gate 0 PULSE(0 12 0 1n 1n 125n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 3, "tag": "280V-async-50kHz",
 "net": """\
* 280V to 5V async buck, 150W, 50kHz
* D=5/280=0.0179, t_on=357n for T=20u
Vin in 0 280
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 68u
C1 out 0 470u
Rload out 0 0.167
Vgate gate 0 PULSE(0 12 0 1n 1n 357n 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 3, "tag": "320V-sync",
 "net": """\
* 320V to 5V synchronous buck, 150W
* D=5/320=0.0156, t_on=156n
Vin in 0 320
M1 in gate sw 0 NMOS W=1 L=1
M2 sw gate2 0 0 NMOS W=1 L=1
L1 sw out 33u
C1 out 0 220u
Rload out 0 0.167
Rbleed sw 0 1Meg
Vgate  gate  0 PULSE(0 12 0    1n 1n 156n  10u)
Vgate2 gate2 0 PULSE(0 12 300n 1n 1n 9.5u  10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.tran 1n 5m
.end"""},

# ── IDX 4: Vin 208-277V → 3.3V, 100W (buck) ────────────────────────────
{"idx": 4, "tag": "208V-async",
 "net": """\
* 208V to 3.3V async buck, 100W
* D=3.3/208=0.0159, t_on=159n, Rload=10.89/100=0.109
Vin in 0 208
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 22u
C1 out 0 470u
Rload out 0 0.109
Vgate gate 0 PULSE(0 12 0 1n 1n 159n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 4, "tag": "277V-async",
 "net": """\
* 277V to 3.3V async buck, 100W
* D=3.3/277=0.0119, t_on=119n
Vin in 0 277
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 47u
C1 out 0 470u
Rload out 0 0.109
Vgate gate 0 PULSE(0 12 0 1n 1n 119n 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 4, "tag": "240V-async-50kHz",
 "net": """\
* 240V to 3.3V async buck, 100W, 50kHz
* D=3.3/240=0.0138, t_on=275n for T=20u
Vin in 0 240
M1 in gate sw 0 NMOS W=1 L=1
D1 0 sw DIODE
L1 sw out 68u
C1 out 0 470u
Rload out 0 0.109
Vgate gate 0 PULSE(0 12 0 1n 1n 275n 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 4, "tag": "220V-sync",
 "net": """\
* 220V to 3.3V synchronous buck, 100W
* D=3.3/220=0.015, t_on=150n
Vin in 0 220
M1 in gate sw 0 NMOS W=1 L=1
M2 sw gate2 0 0 NMOS W=1 L=1
L1 sw out 22u
C1 out 0 220u
Rload out 0 0.109
Rbleed sw 0 1Meg
Vgate  gate  0 PULSE(0 12 0    1n 1n 150n  10u)
Vgate2 gate2 0 PULSE(0 12 300n 1n 1n 9.5u  10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.tran 1n 5m
.end"""},

# ── IDX 5: Vin 12-24V → 380V, 400W (boost) ─────────────────────────────
{"idx": 5, "tag": "12V-boost",
 "net": """\
* 12V to 380V boost, 400W, 100kHz
* D=1-12/380=0.968, t_on=9.68u, Rload=380^2/400=361
* L1 is on the input side (in -> sw), M1 is low-side switch
Vin in 0 12
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 361
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.68u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 5, "tag": "18V-boost",
 "net": """\
* 18V to 380V boost, 400W, 100kHz
* D=1-18/380=0.953, t_on=9.53u
Vin in 0 18
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 361
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.53u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 5, "tag": "24V-boost",
 "net": """\
* 24V to 380V boost, 400W, 100kHz
* D=1-24/380=0.937, t_on=9.37u
Vin in 0 24
L1 in sw 68u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 361
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.37u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 5, "tag": "12V-boost-L220u",
 "net": """\
* 12V to 380V boost, 400W, 100kHz, larger L for lower ripple
Vin in 0 12
L1 in sw 220u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 220u
Rload out 0 361
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.68u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 6: Vin 9-12V → 220V, 250W (boost) ──────────────────────────────
{"idx": 6, "tag": "9V-boost",
 "net": """\
* 9V to 220V boost, 250W, 100kHz
* D=1-9/220=0.959, t_on=9.59u, Rload=220^2/250=193.6
Vin in 0 9
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 193.6
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.59u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 6, "tag": "12V-boost",
 "net": """\
* 12V to 220V boost, 250W, 100kHz
* D=1-12/220=0.945, t_on=9.45u
Vin in 0 12
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 193.6
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.45u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 6, "tag": "10V-boost-50kHz",
 "net": """\
* 10V to 220V boost, 250W, 50kHz
* D=1-10/220=0.955, t_on=19.1u for T=20u
Vin in 0 10
L1 in sw 220u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 220u
Rload out 0 193.6
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 19.1u 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 6, "tag": "9V-boost-L47u",
 "net": """\
* 9V to 220V boost, 250W, 100kHz, smaller L
Vin in 0 9
L1 in sw 47u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 193.6
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.59u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 7: Vin 5-9V → 208V, 100W (boost) ───────────────────────────────
{"idx": 7, "tag": "5V-boost",
 "net": """\
* 5V to 208V boost, 100W, 100kHz
* D=1-5/208=0.976, t_on=9.76u, Rload=208^2/100=432
Vin in 0 5
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 432
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.76u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 7, "tag": "9V-boost",
 "net": """\
* 9V to 208V boost, 100W, 100kHz
* D=1-9/208=0.957, t_on=9.57u
Vin in 0 9
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 432
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.57u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 7, "tag": "7V-boost-50kHz",
 "net": """\
* 7V to 208V boost, 100W, 50kHz
* D=1-7/208=0.966, t_on=19.3u for T=20u
Vin in 0 7
L1 in sw 220u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 220u
Rload out 0 432
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 19.3u 20u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 7, "tag": "5V-boost-L470u",
 "net": """\
* 5V to 208V boost, 100W, 100kHz, large L for low ripple
Vin in 0 5
L1 in sw 470u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 100u
Rload out 0 432
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.76u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 8: Vin 12-24V → 400V, 500W (boost) ─────────────────────────────
{"idx": 8, "tag": "12V-boost",
 "net": """\
* 12V to 400V boost, 500W, 100kHz
* D=1-12/400=0.97, t_on=9.7u, Rload=400^2/500=320
Vin in 0 12
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 220u
Rload out 0 320
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.7u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 8, "tag": "24V-boost",
 "net": """\
* 24V to 400V boost, 500W, 100kHz
* D=1-24/400=0.94, t_on=9.4u
Vin in 0 24
L1 in sw 68u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 220u
Rload out 0 320
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.4u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 8, "tag": "18V-boost",
 "net": """\
* 18V to 400V boost, 500W, 100kHz
* D=1-18/400=0.955, t_on=9.55u
Vin in 0 18
L1 in sw 100u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 220u
Rload out 0 320
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.55u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 8, "tag": "24V-boost-L470u",
 "net": """\
* 24V to 400V boost, 500W, 100kHz, large L
Vin in 0 24
L1 in sw 470u
M1 sw gate 0 0 NMOS W=1 L=1
D1 sw out DIODE
C1 out 0 470u
Rload out 0 320
Rbleed sw 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 9.4u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 9: Vin 9-36V → 24V, 200W (buck-boost, SEPIC) ───────────────────
{"idx": 9, "tag": "12V-SEPIC",
 "net": """\
* 12V to 24V SEPIC buck-boost, 200W, 100kHz
* D=Vout/(Vin+Vout)=24/36=0.667, t_on=6.67u
* Topology: L1 in->sw1, M1 sw1->0, C1 sw1<->sw2, L2 sw2->0, D1 sw2->out
Vin in 0 12
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 470u
Rload out 0 2.88
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 6.67u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 9, "tag": "24V-SEPIC",
 "net": """\
* 24V to 24V SEPIC, 200W (passthrough case, D=0.5)
Vin in 0 24
L1 in sw1 68u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 68u
D1 sw2 out DIODE
C2 out 0 470u
Rload out 0 2.88
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 9, "tag": "36V-SEPIC",
 "net": """\
* 36V to 24V SEPIC, 200W (buck mode: Vin > Vout)
* D=24/(24+36)=0.4, t_on=4u
Vin in 0 36
L1 in sw1 68u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 68u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 2.88
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 4u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 9, "tag": "18V-SEPIC",
 "net": """\
* 18V to 24V SEPIC, 200W (boost-ish: Vin < Vout)
* D=24/(24+18)=0.571, t_on=5.71u
Vin in 0 18
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 47u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 470u
Rload out 0 2.88
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5.71u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 10: Vin 208-480V → 380V, 450W (buck-boost, SEPIC) ──────────────
{"idx": 10, "tag": "240V-SEPIC",
 "net": """\
* 240V to 380V SEPIC, 450W, 100kHz (boost-mode: Vin < Vout)
* D=380/(380+240)=0.613, t_on=6.13u, Rload=380^2/450=321
Vin in 0 240
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 100u
Rload out 0 321
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 6.13u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 10, "tag": "380V-SEPIC",
 "net": """\
* 380V to 380V SEPIC, 450W (passthrough, D=0.5)
Vin in 0 380
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 100u
Rload out 0 321
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 10, "tag": "480V-SEPIC",
 "net": """\
* 480V to 380V SEPIC, 450W (buck-mode: Vin > Vout)
* D=380/(380+480)=0.442, t_on=4.42u
Vin in 0 480
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 100u
Rload out 0 321
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 4.42u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 10, "tag": "350V-SEPIC",
 "net": """\
* 350V to 380V SEPIC, 450W
* D=380/(380+350)=0.521, t_on=5.21u
Vin in 0 350
L1 in sw1 220u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 47u
L2 sw2 0 220u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 321
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5.21u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 11: Vin 12-48V → 36V, 350W (buck-boost, SEPIC) ─────────────────
{"idx": 11, "tag": "24V-SEPIC",
 "net": """\
* 24V to 36V SEPIC, 350W (boost-ish)
* D=36/(36+24)=0.6, t_on=6u, Rload=36^2/350=3.70
Vin in 0 24
L1 in sw1 47u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 47u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 3.70
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 6u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 11, "tag": "36V-SEPIC",
 "net": """\
* 36V to 36V SEPIC, 350W (passthrough, D=0.5)
Vin in 0 36
L1 in sw1 47u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 47u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 3.70
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 11, "tag": "48V-SEPIC",
 "net": """\
* 48V to 36V SEPIC, 350W (buck-mode)
* D=36/(36+48)=0.429, t_on=4.29u
Vin in 0 48
L1 in sw1 47u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 47u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 3.70
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 4.29u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 11, "tag": "12V-SEPIC",
 "net": """\
* 12V to 36V SEPIC, 350W (deep boost)
* D=36/(36+12)=0.75, t_on=7.5u
Vin in 0 12
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 47u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 470u
Rload out 0 3.70
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 7.5u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

# ── IDX 12: Vin 100-277V → 220V, 300W (buck-boost, SEPIC) ──────────────
{"idx": 12, "tag": "150V-SEPIC",
 "net": """\
* 150V to 220V SEPIC, 300W (boost-mode)
* D=220/(220+150)=0.595, t_on=5.95u, Rload=220^2/300=161
Vin in 0 150
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 161
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5.95u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 12, "tag": "220V-SEPIC",
 "net": """\
* 220V to 220V SEPIC, 300W (passthrough D=0.5)
Vin in 0 220
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 161
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 12, "tag": "277V-SEPIC",
 "net": """\
* 277V to 220V SEPIC, 300W (buck-mode)
* D=220/(220+277)=0.443, t_on=4.43u
Vin in 0 277
L1 in sw1 100u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 22u
L2 sw2 0 100u
D1 sw2 out DIODE
C2 out 0 220u
Rload out 0 161
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 4.43u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},

{"idx": 12, "tag": "200V-SEPIC",
 "net": """\
* 200V to 220V SEPIC, 300W
* D=220/(220+200)=0.524, t_on=5.24u
Vin in 0 200
L1 in sw1 220u
M1 sw1 gate 0 0 NMOS W=1 L=1
C1 sw1 sw2 47u
L2 sw2 0 220u
D1 sw2 out DIODE
C2 out 0 470u
Rload out 0 161
Rbleed sw1 0 1Meg
Rbleed1 sw2 0 1Meg
Vgate gate 0 PULSE(0 12 0 1n 1n 5.24u 10u)
.model NMOS NMOS(Vto=1 Kp=2 Lambda=0)
.model DIODE D
.tran 1n 5m
.end"""},
]


# ────────────────────────────────────────────────────────────────────────
# Main: write canonical batches + final JSONL, then run validator
# ────────────────────────────────────────────────────────────────────────

def main():
    """Write hand-crafted SFT pairs to disk and run the validator on each batch.

    Reads the ``SAMPLES`` list, groups entries by constraint index, writes
    each group to a canonical ``batch_sft_claude_inline_idx<N>/`` directory,
    runs the validator, and appends passing pairs to
    ``data/sft/sft_from_claude_inline.jsonl``.
    """
    constraints = load_constraints(
        str(REPO_ROOT / "pipeline" / "data" / "datasets" / "constraints.json")
    )
    print(f"[setup] loaded {len(constraints)} constraints")
    print(f"[setup] {len(SAMPLES)} hand-crafted samples to process")

    # Group by idx, write each group as a batch
    by_idx: dict[int, list[dict]] = {}
    for s in SAMPLES:
        by_idx.setdefault(s["idx"], []).append(s)

    all_pairs: list[dict] = []
    for idx, group in sorted(by_idx.items()):
        constraint = constraints[idx]
        batch_id = f"batch_sft_claude_inline_idx{idx}"
        print(f"\n── idx={idx}  vin {constraint.get('vin_min')}-{constraint.get('vin_max')}V "
              f"→ {constraint.get('vout_target')}V, {constraint.get('power_in')}W  "
              f"({len(group)} samples) ──")

        netlists = [g["net"] for g in group]
        written = write_netlists(netlists=netlists, batchID=batch_id)
        print(f"  wrote {len(written)} files")

        # Validate
        val_results = _run_validator(batch_id)
        n_passed = sum(1 for v in val_results.values() if v.get("passed"))
        print(f"  validator: {n_passed}/{len(val_results)} passed")

        # Build SFT pairs for each passing sample
        prompt = make_prompt(constraint)
        for path, sample in zip(written, group):
            info = val_results.get(path.stem) or val_results.get(path.name) or {}
            if not info.get("passed"):
                fail_checks = [k for k, ok in (info.get("checks") or {}).items() if ok is False]
                print(f"  [skip] {sample['tag']}: {fail_checks[:3]}")
                continue
            all_pairs.append({
                "prompt":     prompt,
                "completion": path.read_text(encoding="utf-8"),
                "fitness":    None,
                "source":     f"{batch_id}/{path.stem}",
                "constraint": {k: v for k, v in constraint.items() if not k.startswith("_")},
                "generator":  "claude-inline-handcrafted",
                "tag":        sample["tag"],
            })

    out = REPO_ROOT / "data" / "sft" / "sft_from_claude_inline.jsonl"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        for r in all_pairs:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    print(f"\n[done] {len(all_pairs)} validator-passing SFT pair(s)")
    print(f"[done] written to {out}")


def _run_validator(batch_id: str) -> dict:
    try:
        from pipeline.netlist_validation.validator import validator
    except ImportError as e:
        print(f"  WARN: validator unavailable ({e})")
        return {}
    val = validator()
    val.validate(batch_id)
    p = REPO_ROOT / "pipeline" / "data" / batch_id / "validation_results.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


if __name__ == "__main__":
    main()
